### ISSUE TITLE
Image support

### ISSUE THREAD

**Issue by Iikeli** [NiftyTreeStudios/Nifty-Markdown-Formatter#3]

**Comment by wptechprodigy** [comment]
Hi @Iikeli 

Trust you are doing good.

I want to build an application that needs to display a markdown in a cell,
in my quest I found your library...

I see it needs enhancement and would love to contribute to the library...

Any guidelines, I need to know!?

**Comment by Iikeli** [comment]
Hi @wptechprodigy as long as you structure the code well, write tests where useful, and add documentation, all is good.

I did notice a while back that Apple also now has a markdown library. I have not yet played around with it myself, so don't know if it will solve your problems. https://github.com/apple/swift-markdown

**Comment by wptechprodigy** [comment]
Thanks @Iikeli...I'll check it out!

**Comment by tsfischer** [comment]
Did this enhancement get off the ground (e.g. on a fork)? Looking for a viable SwiftUI markdown view that handles images. `MarkdownUI` (https://github.com/gonzalezreal/MarkdownUI) looked promising but is hanging/crashing in certain circumstances for us.

**Comment by Iikeli** [comment]
> 

Hey @tsfischer 

This has not been implemented yet. Do you want to look into the implementation or should I invest some time this week?

**Comment by tsfischer** [comment]
If you're able to, that would be awesome. I have not heard back from the owner of `MarkdownUI` on the issue we're having there, and it seems like this library might be the next best alternative. But we would really like to have image support.

**Comment by Iikeli** [comment]
@tsfischer I'll take a look at it during the weekend or early next week. Hopefully can add that functionality for you guys quickly.
